name: Deploy to k8s
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ['self-hosted']
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy Kubenetes
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl get pods 
          kubectl get service
        # run: |
        #   $yamlContent = @"

        #   apiVersion: apps/v1
        #   kind: Deployment #let deployment set spec for deploy
        #   metadata:
        #     name: eshop-web-deployment
        #   spec:
        #     replicas: 3
        #     selector:
        #       matchLabels:
        #         app: eshop-web

        #     template:
        #       metadata:
        #         labels: 
        #           app: eshop-web
        #       spec:
        #         containers:
        #         - name: eshop-web-containerport
        #           image: settawuts17/eshopweb-k8s:1.0
        #           ports:
        #           - containerPort: 3000

        #   --- #end

        #   apiVersion: v1
        #   kind: Service #when deploy result container instance to pod 
        #   metadata:
        #     name: eshop-web-service
        #   spec:
        #     selector: 
        #       app: eshop-web # follow label deployment 
        #     ports:
        #       - protocol: TCP
        #         port: 80
        #         targetPort: 3000
        #     type: LoadBalancer # allow access via other network 
          
        #   "@
        #   $yamlContent | out-file -filePath deployment.yaml
        #   kubectl apply -f deployment.yaml
  